-- ingestion_log
COMMENT ON TABLE "ingestion_log" IS '적재 이력 (모든 적재 사건의 본체 — 작업자/시각/파일/행수). 본 테이블들이 ingestion_id로 이 로그에 연결됨';
COMMENT ON COLUMN "ingestion_log"."table_name" IS '대상 테이블명';
COMMENT ON COLUMN "ingestion_log"."snapshot_date" IS '적재 대상 스냅샷 기준일 (파일 기준일)';
COMMENT ON COLUMN "ingestion_log"."operation" IS 'insert | reload 등';
COMMENT ON COLUMN "ingestion_log"."row_count" IS '처리된 행 수';
COMMENT ON COLUMN "ingestion_log"."uploaded_by" IS '작업자 (Profile.id / Supabase Auth 사용자)';
COMMENT ON COLUMN "ingestion_log"."source_file" IS '업로드한 원본 파일명';

-- coupang_growth_inbound_template
COMMENT ON TABLE "coupang_growth_inbound_template" IS '쿠팡 그로스 입고 생성 템플릿 (전체 등록 상품)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."ingestion_id" IS '어느 적재 배치인지';
COMMENT ON COLUMN "coupang_growth_inbound_template"."coupang_seller_account_id" IS '쿠팡 판매자 계정';
COMMENT ON COLUMN "coupang_growth_inbound_template"."snapshot_date" IS '스냅샷 기준일 (파일 기준일)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."registered_product_name" IS '등록상품명 (B)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."option_name" IS '옵션명 (C)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."selling_price" IS '판매가 (D)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."exposed_product_id" IS '노출상품 ID (E)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."registered_product_id" IS '등록상품 ID (F)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."option_id" IS '옵션 ID (G)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."selling_method" IS '판매 방식 (H)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."sales_2025_total" IS '25년 총계 (I)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."sales_2026_total" IS '26년 총계 (J)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."sales_2026_03" IS '26년 03월 (K)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."sales_2026_04" IS '26년 04월 (L)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."sales_2026_05" IS '26년 05월 (M)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."sales_last_14days" IS '지난 14일 (N)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."qty_sold_2weeks" IS '2주간 판매수량 (O)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."qty_sold_1week" IS '1주간 판매수량 (P)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."seller_fee_rate" IS '판매자 수수료율 (Q)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."seller_fee" IS '판매자 수수료 (R)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."cfs_estimated_fee" IS '쿠팡풀필먼트서비스 예상 요금(개당) (S)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."base_discount" IS '기본 할인액 (T)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."discounted_estimated_fee" IS '할인 적용 예상 요금 (U)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."est_sales_2weeks_by_qty" IS '입고수량에 따른 2주간 예상 매출 (W)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."shelf_life_days_input" IS '유통기간 입력 (X)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."expiry_date" IS '유통(소비)기한 (Y)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."manufacture_date" IS '제조일자 (Z)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."production_year" IS '생산연도 (AA)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."product_barcode" IS '상품바코드 (AB)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."product_size" IS '상품 사이즈 (AC)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."handle_with_care" IS '취급주의여부 (AD)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."available_stock" IS '판매가능재고 (AE)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."est_stockout_date" IS '예상 재고 소진일 (AF)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."category" IS '카테고리 (AG)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."parallel_import" IS '병행수입 여부 (AH)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."tax_type" IS '과세유형 (AI)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."sku_id" IS 'SKU ID (AJ)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."req_exp_date" IS 'Req exp date (AK)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."req_man_date" IS 'Req man date (AL)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."req_prod_year" IS 'Req prod year (AM)';
COMMENT ON COLUMN "coupang_growth_inbound_template"."created_at" IS '이 행 적재 시각';

-- coupang_growth_inventory_health
COMMENT ON TABLE "coupang_growth_inventory_health" IS '쿠팡 그로스 재고 현황 (입고되어 재고가 잡힌 상품)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."ingestion_id" IS '어느 적재 배치인지';
COMMENT ON COLUMN "coupang_growth_inventory_health"."coupang_seller_account_id" IS '쿠팡 판매자 계정';
COMMENT ON COLUMN "coupang_growth_inventory_health"."snapshot_date" IS '스냅샷 기준일 (파일 기준일)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."inventory_id" IS 'Inventory ID (B)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."option_id" IS 'Option ID (C) — template과 논리적 연관, FK 미설정';
COMMENT ON COLUMN "coupang_growth_inventory_health"."sku_id" IS 'SKU ID (D)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."product_name" IS 'Product name (E)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."option_name" IS 'Option name (F)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."offer_condition" IS 'Offer condition (G)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."orderable_quantity" IS 'Orderable quantity (real-time) (H)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."pending_inbounds" IS 'Pending inbounds (real-time) (I)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."item_winner" IS 'Item winner (J)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."recent_sales_7days" IS 'Recent sales (Excluding bundle sales) Last 7 days (K)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."recent_sales_30days" IS 'Recent sales (Excluding bundle sales) Last 30 days (L)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."recent_sales_qty_7days" IS 'Recent sales quantity Last 7 days (M)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."recent_sales_qty_30days" IS 'Recent sales quantity Last 30 days (N)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."recommended_inbound_qty" IS 'Recommended inbound quantity (O)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."recommended_inbound_date" IS 'Recommended inbound date (P)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."days_of_cover" IS 'Days of cover (Q)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."monthly_storage_fee" IS 'Monthly storage fee (R)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."sku_age_1_30" IS 'Sku age (D-1) 1~30 days (S)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."sku_age_31_45" IS 'Sku age (D-1) 31~45 days (T)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."sku_age_46_60" IS 'Sku age (D-1) 46~60 days (U)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."sku_age_61_120" IS 'Sku age (D-1) 61~120 days (V)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."sku_age_121_180" IS 'Sku age (D-1) 121~180 days (W)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."sku_age_181_plus" IS 'Sku age (D-1) 181+ days (X)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."customer_returns_30days" IS 'Customer returns last 30 days (D-1) (Y)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."season" IS 'Season (Z)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."product_listing_date" IS 'Product listing date (AA)';
COMMENT ON COLUMN "coupang_growth_inventory_health"."created_at" IS '이 행 적재 시각';
